### ISSUE TITLE
how to get stb serial number

### ISSUE THREAD

**Issue by invisiblecoder99** [DarkPark/stb-demo#4]
can you give me javascript code to get stb serial number

**Comment by DarkPark** [comment]
```js
gSTB.GetDeviceSerialNumber();
```
please use official documentation - http://soft.infomir.com.ua/mag250/Doc/JS%20API%20MAG200%20(Rev%201.20).pdf
or even better - https://wiki.infomir.eu/eng/stb-webkit/for-developers
